name: super_tech
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  share: ^2.0.4
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Images/Logo/App icon.png"
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/Laptop/All Images/a1.jpg
    - Images/Laptop/All Images/a2.jpg
    - Images/Laptop/All Images/b1.jpg
    - Images/Laptop/All Images/b2.jpg
    - Images/Laptop/All Images/c1.jpg
    - Images/Laptop/All Images/c2.jpg
    - Images/Laptop/All Images/c3.jpg
    - Images/Laptop/All Images/c4.jpg
    - Images/Laptop/All Images/d1.jpg
    - Images/Laptop/All Images/d2.jpg
    - Images/Laptop/All Images/d3.jpg
    - Images/Laptop/All Images/d4.jpg
    - Images/Laptop/All Images/e1.jpg
    - Images/Laptop/All Images/e2.jpg
    - Images/Laptop/All Images/f1.jpg
    - Images/Laptop/All Images/f2.jpg
    - Images/Laptop/All Images/g1.jpg
    - Images/Laptop/All Images/g2.jpg
    - Images/Laptop/All Images/g3.jpg
    - Images/Laptop/All Images/g4.jpg
    - Images/Laptop/All Images/h1.jpg
    - Images/Laptop/All Images/h2.jpg
    - Images/Laptop/All Images/h3.jpg
    - Images/Laptop/All Images/i1.jpg
    - Images/Laptop/All Images/i2.jpg
    - Images/Laptop/All Images/j1.jpg
    - Images/Laptop/All Images/j2.jpg
    - Images/Laptop/All Images/j3.jpg
    - Images/Laptop/All Images/k1.jpg
    - Images/Laptop/All Images/k2.jpg
    - Images/Laptop/All Images/l1.jpg
    - Images/Laptop/All Images/l2.jpg
    - Images/Laptop/All Images/l3.jpg
    - Images/Laptop/All Images/n1.jpg
    - Images/Laptop/All Images/n2.jpg
    - Images/Laptop/All Images/n3.jpg
    - Images/Laptop/01.jpg
    - Images/Laptop/02.jpeg
    - Images/Home top Picture/01.jpg #animation Picture
    - Images/Home top Picture/02.jpg
    - Images/Home top Picture/03.jpg
    - Images/Home top Picture/04.jpg
    - Images/Home top Picture/05.jpg
    - Images/Logo/logo.png #Super Tech Logo
    - Images/Logo/Flogo.png
    - Images/Logo/App icon.png
    - Images/Catagory Icons/01.jpg #category icons
    - Images/Catagory Icons/02.png
    - Images/Catagory Icons/03.jpg
    - Images/Catagory Icons/04.png
    - Images/Catagory Icons/05.png
    - Images/Catagory Icons/06.png
    - Images/Catagory Icons/07.png
    - Images/Catagory Icons/08.png
    - Images/Catagory Icons/09.jpg
    - Images/Catagory Icons/10.jpg
    - Images/Catagory Icons/11.png
    - Images/Catagory Icons/12.png
    - Images/login image/01.jpg #login images
    - Images/login image/03.jpg
    - Images/Logo/App icon.png
    - Images/Pc/a1.jpg #Pc Pictures
    - Images/Pc/a2.jpg
    - Images/Pc/a3.jpg
    - Images/Pc/b1.jpg
    - Images/Pc/b2.jpg
    - Images/Pc/b3.jpg
    - Images/Pc/c1.jpg
    - Images/Pc/c2.jpg
    - Images/Pc/c3.jpg
    - Images/Pc/d.jpg
    - Images/Pc/e1.jpg
    - Images/Pc/e2.jpg
    - Images/Pc/e3.jpg
    - Images/Pc/f1.jpg
    - Images/Pc/f2.jpg
    - Images/Pc/f3.jpg
    - Images/Pc/g.jpg
    - Images/Pc/h.jpg
    - Images/Pc/i.jpg
    - Images/Pc/j1.jpg
    - Images/Pc/j2.jpg
    - Images/SSD/a1.jpg #SSD Card Picture
    - Images/SSD/a2.jpg
    - Images/SSD/b.jpg
    - Images/SSD/c1.jpg
    - Images/SSD/c2.jpg
    - Images/SSD/d.jpg
    - Images/SSD/e1.jpg
    - Images/SSD/e2.jpg
    - Images/SSD/e3.jpg
    - Images/SSD/f.jpg
    - Images/SSD/g.jpg
    - Images/SSD/h1.jpg
    - Images/SSD/h2.jpg
    - Images/SSD/h3.jpg
    - Images/SSD/i1.jpg
    - Images/SSD/i2.jpg
    - Images/SSD/j1.jpg
    - Images/SSD/j2.jpg
    - Images/SSD/j3.jpg




  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
